apiVersion: v1
kind: Service
metadata:
  name: chatllm-backendapi-service
spec:
  selector:
    app: chatllmapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer