services:
  backend:
    image: ghcr.io/adribaeza/llm-tinyllama-backend:latest
    volumes:
      - ./backend/api:/api
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=api.main
      - VARIABLE_NAME=api
      - SERVICE_TOKEN=myllservicetoken2024

  frontend:
    image: ghcr.io/adribaeza/llm-tinyllama-frontend:latest
    volumes:
      - ./frontend/app:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - SERVICE_TOKEN=myllservicetoken2024
      - RUNNING_IN_DOCKER=true
      - DOCKER_API_URL=http://host.docker.internal:8000/api/v1/chat
    
