services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/api:/api
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=api.main
      - VARIABLE_NAME=api
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    env_file:
      - ./frontend/.env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - SERVICE_TOKEN=${SERVICE_TOKEN}
    env_file:
      - ./backend/.env