apiVersion: v1
kind: Service
metadata:
  name: chatllm-frontend-service
spec:
  selector:
    app: chatllm-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer